//+------------------------------------------------------------------+
//| NeoFL Executioner EA                                             |
//| Universal EA: NeoFL supplies decisions; this EA executes only.  |
//+------------------------------------------------------------------+
#property strict
#property version "3.0"
#property description "Universal NeoFL execution-only EA with account-specific API routing"

// Paste the account-specific handshake URL generated by the NeoFL Gateway.
// Example: https://.../api/handshake?account=318558926&key=...
input string NeoFL_API_URL = "";
input int    HandshakeIntervalSeconds = 15;

long   g_account = 0;
string g_server  = "";
bool   g_authorized = false;
datetime g_last_handshake = 0;

string EnvironmentName()
{
   ENUM_ACCOUNT_TRADE_MODE mode=(ENUM_ACCOUNT_TRADE_MODE)AccountInfoInteger(ACCOUNT_TRADE_MODE);
   return mode==ACCOUNT_TRADE_MODE_DEMO ? "DEMO" : "LIVE";
}

long RouteAccount()
{
   int p=StringFind(NeoFL_API_URL,"account=");
   if(p<0) return 0;
   p+=8;
   int e=StringFind(NeoFL_API_URL,"&",p);
   string value=e<0 ? StringSubstr(NeoFL_API_URL,p) : StringSubstr(NeoFL_API_URL,p,e-p);
   return (long)StringToInteger(value);
}

bool RuntimeIdentityOK()
{
   long account=(long)AccountInfoInteger(ACCOUNT_LOGIN);
   string server=AccountInfoString(ACCOUNT_SERVER);
   if(account!=g_account) return false;
   if(server!=g_server) return false;
   if(RouteAccount()!=g_account) return false;
   return true;
}

bool Handshake()
{
   if(!RuntimeIdentityOK())
   {
      g_authorized=false;
      Print("NeoFL BLOCKED: EA account/server does not match the account-specific API route.");
      return false;
   }

   string headers="Content-Type: application/json\r\n";
   string payload=StringFormat("{\"account_number\":%I64d,\"server\":\"%s\",\"environment\":\"%s\"}",g_account,g_server,EnvironmentName());
   char data[];
   StringToCharArray(payload,data,0,StringLen(payload),CP_UTF8);
   char result[];
   string result_headers="";

   ResetLastError();
   int http=WebRequest("POST",NeoFL_API_URL,headers,10000,data,result,result_headers);
   if(http==-1)
   {
      g_authorized=false;
      Print("NeoFL handshake WebRequest failed. Error=",GetLastError(),". Add the gateway domain to MT5 allowed WebRequest URLs.");
      return false;
   }

   string body=CharArrayToString(result,0,-1,CP_UTF8);
   g_authorized=(http>=200 && http<300 && StringFind(body,"\"accepted\":true")>=0);
   g_last_handshake=TimeCurrent();

   if(g_authorized)
      Print("NeoFL account route authorized: account=",g_account," server=",g_server);
   else
      Print("NeoFL BLOCKED: gateway rejected account route. HTTP=",http," response=",body);

   return g_authorized;
}

int OnInit()
{
   g_account=(long)AccountInfoInteger(ACCOUNT_LOGIN);
   g_server=AccountInfoString(ACCOUNT_SERVER);

   if(NeoFL_API_URL=="")
   {
      Print("NeoFL BLOCKED: paste the account-specific API URL from the NeoFL Gateway.");
      return INIT_FAILED;
   }
   if(RouteAccount()!=g_account)
   {
      Print("NeoFL BLOCKED: API route account does not match this MT5 account.");
      return INIT_FAILED;
   }

   EventSetTimer(MathMax(1,HandshakeIntervalSeconds));
   Handshake();
   Print("NeoFL Executioner started. Account=",g_account," Server=",g_server);
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   EventKillTimer();
}

void OnTick()
{
   // No local strategy or signal generation exists here.
   // NeoFL Brain remains the sole decision maker.
}

void OnTimer()
{
   Handshake();

   // Fail-closed execution boundary:
   // order execution is permitted only after a future verified command
   // transport is added. This EA never invents or generates trades locally.
   if(!g_authorized) return;
}

// IMPORTANT:
// 1. The same EA file is distributed to every user.
// 2. Each user pastes only their own account-specific API URL.
// 3. The gateway validates account number, broker/server, environment and key.
// 4. A route/account mismatch blocks the EA.
// 5. No strategy or autonomous signal generation is contained in this EA.
