-- NeoFL persistent memory schema.
-- Apply this migration to the NeoFL Supabase project before enabling persistent runtime memory.

create table if not exists public.brain_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brain text not null,
  event_type text not null,
  symbol text,
  state text,
  confidence double precision,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.soul_decisions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text,
  symbol text,
  state text not null,
  confidence double precision,
  execution_authorized boolean not null default false,
  rationale text not null default '',
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.agent_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_id text,
  mode text not null default 'analyze',
  symbol text,
  input_text text not null,
  response jsonb,
  status text not null default 'accepted'
);

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  hypothesis text,
  outcome text,
  lesson text,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.experiments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  status text not null default 'sandbox',
  hypothesis text not null,
  conditions jsonb not null default '{}'::jsonb,
  results jsonb not null default '{}'::jsonb
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  account_key text not null unique,
  platform text not null,
  broker text,
  environment text not null default 'DEMO',
  enabled boolean not null default false,
  execution_authorized boolean not null default false,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_brain_events_created_at on public.brain_events(created_at desc);
create index if not exists idx_brain_events_brain on public.brain_events(brain, created_at desc);
create index if not exists idx_soul_decisions_created_at on public.soul_decisions(created_at desc);
create index if not exists idx_agent_requests_created_at on public.agent_requests(created_at desc);
create index if not exists idx_learning_events_created_at on public.learning_events(created_at desc);
create index if not exists idx_experiments_created_at on public.experiments(created_at desc);

alter table public.brain_events enable row level security;
alter table public.soul_decisions enable row level security;
alter table public.agent_requests enable row level security;
alter table public.learning_events enable row level security;
alter table public.experiments enable row level security;
alter table public.accounts enable row level security;

-- No anonymous/public write policies are created. Server-side service-role access is
-- required until proper user authentication and tenant/account policies are defined.
